spring:
  datasource:
    url: jdbc:postgresql://c-crescendo-database.niozuvgjoztwa6.postgres.cosmos.azure.com:5432/citus
    username: citus
    password: apple080915!
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

    show-sql: true

server:
  port: 8088
